
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.heading = QtWidgets.QLabel(self.centralwidget)
        self.heading.setGeometry(QtCore.QRect(250, 90, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.heading.setFont(font)
        self.heading.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.heading.setMouseTracking(False)
        self.heading.setAlignment(QtCore.Qt.AlignCenter)
        self.heading.setObjectName("heading")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 150, 568, 31))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.asset_dashboard = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.asset_dashboard.setObjectName("asset_dashboard")
        self.gridLayout_4.addWidget(self.asset_dashboard, 0, 3, 1, 1)
        self.manufacturing_dashboard_button = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.manufacturing_dashboard_button.setObjectName("manufacturing_dashboard_button")
        self.gridLayout_4.addWidget(self.manufacturing_dashboard_button, 0, 2, 1, 1)
        self.stock_dashboard_button = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.stock_dashboard_button.setObjectName("stock_dashboard_button")
        self.gridLayout_4.addWidget(self.stock_dashboard_button, 0, 1, 1, 1)
        self.account_dashboard_button = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.account_dashboard_button.setObjectName("account_dashboard_button")
        self.gridLayout_4.addWidget(self.account_dashboard_button, 0, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(610, 150, 191, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 210, 781, 231))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.assets_button = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.assets_button.setObjectName("assets_button")
        self.gridLayout_5.addWidget(self.assets_button, 2, 2, 1, 1)
        self.payable_button = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.payable_button.setObjectName("payable_button")
        self.gridLayout_5.addWidget(self.payable_button, 1, 0, 1, 1)
        self.project_button = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.project_button.setObjectName("project_button")
        self.gridLayout_5.addWidget(self.project_button, 3, 0, 1, 1)
        self.manufacturing_button = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.manufacturing_button.setObjectName("manufacturing_button")
        self.gridLayout_5.addWidget(self.manufacturing_button, 2, 1, 1, 1)
        self.stock_button = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.stock_button.setObjectName("stock_button")
        self.gridLayout_5.addWidget(self.stock_button, 2, 0, 1, 1)
        self.master_reports_button = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.master_reports_button.setObjectName("master_reports_button")
        self.gridLayout_5.addWidget(self.master_reports_button, 3, 2, 1, 1)
        self.accounts_button = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.accounts_button.setObjectName("accounts_button")
        self.gridLayout_5.addWidget(self.accounts_button, 0, 0, 1, 1)
        self.financial_reports_button = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.financial_reports_button.setObjectName("financial_reports_button")
        self.gridLayout_5.addWidget(self.financial_reports_button, 0, 1, 1, 1)
        self.buying_button = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.buying_button.setObjectName("buying_button")
        self.gridLayout_5.addWidget(self.buying_button, 1, 1, 1, 1)
        self.master_data_button = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.master_data_button.setObjectName("master_data_button")
        self.gridLayout_5.addWidget(self.master_data_button, 3, 1, 1, 1)
        self.receivable_button = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.receivable_button.setObjectName("receivable_button")
        self.gridLayout_5.addWidget(self.receivable_button, 0, 2, 1, 1)
        self.selling_button = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.selling_button.setObjectName("selling_button")
        self.gridLayout_5.addWidget(self.selling_button, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionSave_all = QtWidgets.QAction(MainWindow)
        self.actionSave_all.setObjectName("actionSave_all")
        self.actionSave_as_Templates = QtWidgets.QAction(MainWindow)
        self.actionSave_as_Templates.setObjectName("actionSave_as_Templates")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionSave_Image = QtWidgets.QAction(MainWindow)
        self.actionSave_Image.setObjectName("actionSave_Image")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRe_do = QtWidgets.QAction(MainWindow)
        self.actionRe_do.setObjectName("actionRe_do")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSelect_All = QtWidgets.QAction(MainWindow)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionOption1 = QtWidgets.QAction(MainWindow)
        self.actionOption1.setObjectName("actionOption1")
        self.actionOption2 = QtWidgets.QAction(MainWindow)
        self.actionOption2.setObjectName("actionOption2")
        self.actionOption3 = QtWidgets.QAction(MainWindow)
        self.actionOption3.setObjectName("actionOption3")
        self.actionOption4 = QtWidgets.QAction(MainWindow)
        self.actionOption4.setObjectName("actionOption4")
        self.actionOption5 = QtWidgets.QAction(MainWindow)
        self.actionOption5.setObjectName("actionOption5")
        self.actionOption6 = QtWidgets.QAction(MainWindow)
        self.actionOption6.setObjectName("actionOption6")
        self.actionOption7 = QtWidgets.QAction(MainWindow)
        self.actionOption7.setObjectName("actionOption7")
        self.actionOption8 = QtWidgets.QAction(MainWindow)
        self.actionOption8.setObjectName("actionOption8")
        self.actionOption9 = QtWidgets.QAction(MainWindow)
        self.actionOption9.setObjectName("actionOption9")
        self.actionPreference = QtWidgets.QAction(MainWindow)
        self.actionPreference.setObjectName("actionPreference")
        self.actionSystem_Settings = QtWidgets.QAction(MainWindow)
        self.actionSystem_Settings.setObjectName("actionSystem_Settings")
        self.actionMinimize = QtWidgets.QAction(MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionMaximize = QtWidgets.QAction(MainWindow)
        self.actionMaximize.setObjectName("actionMaximize")
        self.actionClose_2 = QtWidgets.QAction(MainWindow)
        self.actionClose_2.setObjectName("actionClose_2")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionManage_Extentions = QtWidgets.QAction(MainWindow)
        self.actionManage_Extentions.setObjectName("actionManage_Extentions")
        self.actionLibrary = QtWidgets.QAction(MainWindow)
        self.actionLibrary.setObjectName("actionLibrary")
        self.actionSystem_Update = QtWidgets.QAction(MainWindow)
        self.actionSystem_Update.setObjectName("actionSystem_Update")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionSave_all)
        self.menuFile.addAction(self.actionSave_as_Templates)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionSave_Image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRe_do)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuView.addAction(self.actionOption1)
        self.menuView.addAction(self.actionOption2)
        self.menuView.addAction(self.actionOption3)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionOption4)
        self.menuView.addAction(self.actionOption5)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionOption6)
        self.menuView.addAction(self.actionOption7)
        self.menuView.addAction(self.actionOption8)
        self.menuView.addAction(self.actionOption9)
        self.menuSettings.addAction(self.actionPreference)
        self.menuSettings.addAction(self.actionSystem_Settings)
        self.menuWindow.addAction(self.actionMinimize)
        self.menuWindow.addAction(self.actionMaximize)
        self.menuWindow.addAction(self.actionClose_2)
        self.menuWindow.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionManage_Extentions)
        self.menuHelp.addAction(self.actionLibrary)
        self.menuHelp.addAction(self.actionSystem_Update)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.heading.setText(_translate("MainWindow", "Bea-Con Knit Wear Limited"))
        self.asset_dashboard.setText(_translate("MainWindow", "Asset Dashboard"))
        self.manufacturing_dashboard_button.setText(_translate("MainWindow", "Manufacture Dashboard"))
        self.stock_dashboard_button.setText(_translate("MainWindow", "Stock Dashboard"))
        self.account_dashboard_button.setText(_translate("MainWindow", "Accout Dashboard"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Company 1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "New Item"))
        self.assets_button.setText(_translate("MainWindow", "Assets"))
        self.payable_button.setText(_translate("MainWindow", "Payable"))
        self.project_button.setText(_translate("MainWindow", "Project"))
        self.manufacturing_button.setText(_translate("MainWindow", "Manufacturing"))
        self.stock_button.setText(_translate("MainWindow", "Stock"))
        self.master_reports_button.setText(_translate("MainWindow", "Master Reports"))
        self.accounts_button.setText(_translate("MainWindow", "Accounts"))
        self.financial_reports_button.setText(_translate("MainWindow", "Financial Reports"))
        self.buying_button.setText(_translate("MainWindow", "Buying"))
        self.master_data_button.setText(_translate("MainWindow", "Master Data"))
        self.receivable_button.setText(_translate("MainWindow", "Receivable"))
        self.selling_button.setText(_translate("MainWindow", "Selling"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as.."))
        self.actionSave_all.setText(_translate("MainWindow", "Save all"))
        self.actionSave_as_Templates.setText(_translate("MainWindow", "Save as Templates.."))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionSave_Image.setText(_translate("MainWindow", "Save Image"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRe_do.setText(_translate("MainWindow", "Re-do"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionSelect_All.setText(_translate("MainWindow", "Select all"))
        self.actionOption1.setText(_translate("MainWindow", "Option1"))
        self.actionOption2.setText(_translate("MainWindow", "Option2"))
        self.actionOption3.setText(_translate("MainWindow", "Option3"))
        self.actionOption4.setText(_translate("MainWindow", "Option4"))
        self.actionOption5.setText(_translate("MainWindow", "Option5"))
        self.actionOption6.setText(_translate("MainWindow", "Option6"))
        self.actionOption7.setText(_translate("MainWindow", "Option7"))
        self.actionOption8.setText(_translate("MainWindow", "Option8"))
        self.actionOption9.setText(_translate("MainWindow", "Option9"))
        self.actionPreference.setText(_translate("MainWindow", "Preference"))
        self.actionSystem_Settings.setText(_translate("MainWindow", "System Settings"))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize"))
        self.actionMaximize.setText(_translate("MainWindow", "Maximize"))
        self.actionClose_2.setText(_translate("MainWindow", "Close"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionManage_Extentions.setText(_translate("MainWindow", "Manage Extentions"))
        self.actionLibrary.setText(_translate("MainWindow", "Library"))
        self.actionSystem_Update.setText(_translate("MainWindow", "System Update"))
        
        
        